# Generated by Django 3.2.8 on 2023-01-01 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('presented_by', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('event_type', models.CharField(choices=[('departmental', 'Departmetal'), ('informal', 'Informal'), ('club', 'Club')], max_length=20)),
                ('brochure_link', models.URLField()),
                ('register_link', models.URLField()),
                ('image', models.ImageField(upload_to='event_images')),
                ('register_timestamp', models.DateTimeField()),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
                ('event_complete', models.BooleanField(default=False)),
                ('venue', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=250)),
                ('details', models.TextField()),
                ('image', models.ImageField(upload_to='exhibition_images')),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
                ('venue', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GuestTalk',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('guest_name', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=250)),
                ('details', models.TextField()),
                ('register_link', models.URLField()),
                ('image', models.ImageField(upload_to='guest_images')),
                ('register_timestamp', models.DateTimeField()),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
                ('venue', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='mechandise_images')),
                ('price', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OrganisingTeamMember',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team_images')),
                ('designation', models.CharField(max_length=100)),
                ('linkedin', models.URLField()),
                ('contact', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='sponsor_logos')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('position', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=250)),
                ('details', models.TextField()),
                ('register_link', models.URLField()),
                ('image', models.ImageField(upload_to='workshop_images')),
                ('register_timestamp', models.DateTimeField()),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
                ('venue', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
