# Generated by Django 3.2.8 on 2023-01-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230101_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisingteammember',
            name='github',
            field=models.URLField(default='github.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisingteammember',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
