# Generated by Django 3.2.8 on 2023-01-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230108_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team_images')),
                ('designation', models.CharField(max_length=100)),
                ('linkedin', models.URLField()),
                ('github', models.URLField()),
                ('instagram', models.URLField(blank=True, null=True)),
                ('contact', models.CharField(max_length=20)),
            ],
        ),
    ]
